name: Java CI with Maven Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies for update script
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update webapp assets and capture version
        id: update_webapp
        run: |
          chmod +x ./scripts/update-webapp.sh
          ./scripts/update-webapp.sh --ci >> $GITHUB_ENV

      - name: Generate release notes
        run: |
          chmod +x ./scripts/generate-notes.sh
          ./scripts/generate-notes.sh > release_notes.md

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get artifact path and name
        run: |
          ls -R target
          JAR_PATH=$(find target -name "sessionflow.jar" -print -quit)
          if [ -z "$JAR_PATH" ]; then
            echo "::error::JAR file not found in target directory after build."
            exit 1
          fi
          echo "Found JAR at: $JAR_PATH"
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          
      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes-file release_notes.md \
            "${{ env.JAR_PATH }}" 